repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: file-contents-sorter
        files: requirements/base.txt
        args: [--ignore-case]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: git@github.com:zricethezav/gitleaks.git
    rev: v8.15.0
    hooks:
    -   id: gitleaks
